config/routes.rb
Rails.application.routes.draw do
  resources :market_values do 
  	collection do
  		get "calculator"
  		post "result"
  	end
  end
  devise_for :users
  root "market_values#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direction.rb
class Direction < ApplicationRecord
end

app/models/market_value.rb
class MarketValue < ApplicationRecord
  belongs_to :direction
  belongs_to :user
  validates :stock_price, presence: true,  :numericality => {:greater_than =>0}
  validates :strike_price, presence: true,  :numericality => {:greater_than =>0}
  validates :volatility, presence: true,  :numericality => {:greater_than =>0,:less_than=>100}
  validates :interest_rate, presence: true,  :numericality => {:greater_than =>0,:less_than=>100}
  validates :maturity_time, presence: true,  :numericality => {:greater_than =>0}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :market_values
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  layout 'admin_lte_2'

  protect_from_forgery with: :exception
end

app/controllers/market_values_controller.rb
class MarketValuesController < ApplicationController
  before_action :set_market_value, only: [:show, :edit, :update, :destroy]


  def calculator
    @market_value = MarketValue.new
  end

  def result
    @market_value = MarketValue.new(market_value_params)
    if @market_value.valid?
      @status = true
      @result = BlackScholeEquation::Calculator.new(@market_value)
      @time , @put ,@call = @result.time_graph
    else
      @status = false
    end
  end

  # GET /market_values
  # GET /market_values.json
  def index
    @market_values = MarketValue.all.where(:user_id=>current_user.id).paginate(:page => params[:page], :per_page => 7)
    @market_value = MarketValue.new
  end

  # GET /market_values/1
  # GET /market_values/1.json
  def show
    @result = BlackScholeEquation::Calculator.new(@market_value)
  end

  # GET /market_values/new
  def new
    @market_value = MarketValue.new
  end

  # GET /market_values/1/edit
  def edit
  end

  # POST /market_values
  # POST /market_values.json
  def create
    @market_value = MarketValue.new(market_value_params)
    if @market_value.save
      @market_value = MarketValue.new
      @market_values = MarketValue.all.where(:user_id=>current_user.id).paginate(:page => params[:page], :per_page => 7)
      @status = true
    else
      @status = false
    end
  end

  # PATCH/PUT /market_values/1
  # PATCH/PUT /market_values/1.json
  def update
    if @market_value.update(market_value_params)
      @market_value = MarketValue.new
      @market_values = MarketValue.all.where(:user_id=>current_user.id).paginate(:page => params[:page], :per_page => 7)
      @status = true
    else
      @status = false
    end
  end

  # DELETE /market_values/1
  # DELETE /market_values/1.json
  def destroy
    @market_value.destroy
    @market_value = MarketValue.new
    @market_values = MarketValue.all.where(:user_id=>current_user.id).paginate(:page => params[:page], :per_page => 7)
    @status = true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_market_value
      @market_value = MarketValue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def market_value_params
      params.require(:market_value).permit(:stock_price, :volatility, :interest_rate, :maturity_time, :strike_price, :direction_id,:user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/market_values_helper.rb
module MarketValuesHelper
end

app/views/layouts/_admin_lte_2_header.html.erb
<header class="main-header">
  <nav class="navbar navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <a href="/" class="navbar-brand"><b>Black</b>Scholes</a>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
          <i class="fa fa-bars"></i>
        </button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
        <ul class="nav navbar-nav">
          <li><a href="/market_values">Home <span class="sr-only">(current)</span></a></li>
          <li><a href="/market_values/calculator">Calculator</a></li>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- User Account Menu -->
          <li class="dropdown user user-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="hidden-xs">Alexander Pierce</span>
            </a>
            <ul class="dropdown-menu">
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <%= link_to('Sign out', destroy_user_session_path, :method => :delete,:class=>"btn btn-default btn-flat") %>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
      <!-- /.navbar-custom-menu -->
    </div>
    <!-- /.container-fluid -->
  </nav>
  </header>

app/views/layouts/admin_lte_2.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Black Scholes</title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>

<body class="skin-blue layout-top-nav <%= params[:controller].parameterize %> <%= action_name %>">
  <div class="wrapper">

    <%= render partial: 'layouts/admin_lte_2_header' %>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      

      <!-- Main content -->
      <section class="content">
        <% if notice %>
          <div class="alert alert-success alert-dismissable">
            <i class="fa fa-check"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b><%= notice %></b>
          </div>
        <% end %>

        <% if alert %>
          <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b><%= alert %></b>
          </div>
        <% end %>
        <%= yield %>
      </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

  </div><!-- ./wrapper -->

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>
<style type="text/css">
      a
      {
        text-decoration: none !important;
        background: transparent !important;
      }
      .hover:hover
      {
        background : #EAEAEA !important;
      }
      [class^='select2'] {
        border-radius: 0px !important;
      }
      .box-shadow:hover
      {
        box-shadow : 0 3px 6px 0 rgba(0, 0, 0, 0.2) !important;
      }
      .box
      {
        border-radius: 0 0 0 0;
      }
      .box .box-header 
      {
        border-radius: 0 0 0 0;
      }
      .box .box-footer 
      {
        border-radius: 0 0 0 0;
      }
      .btn-primary 
      {
        background-color: #337ab7 !important;
        color: white;
      }
      .btn-success 
      {
        background-color: #5cb85c !important;
      }
      .btn-warning 
      {
        background-color: #f0ad4e !important;
      }
      .btn-info
      {
        background-color: #5bc0de !important;
      }
      .btn-danger {
        background-color: #d9534f !important;
      }
      .skin-blue .wrapper, .skin-blue .main-sidebar, .skin-blue .left-side {
        background-color: #e4e4e4 !important;
      }
      .btn-primary:hover, .btn-primary:active, .btn-primary.hover {
          background-color: #337ab7 !important;
          color: white;
      }
    </style>

app/views/layouts/admin_lte_2_login.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Black Scholes</title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body class="login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="/"><b>Black</b>Scholes</a>
  </div><!-- /.login-logo -->
    <%= yield %>
</div><!-- /.login-box -->

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>
<style type="text/css">
      a
      {
        text-decoration: none !important;
        background: transparent !important;
      }
      .hover:hover
      {
        background : #EAEAEA !important;
      }
      [class^='select2'] {
        border-radius: 0px !important;
      }
      .box-shadow:hover
      {
        box-shadow : 0 3px 6px 0 rgba(0, 0, 0, 0.2) !important;
      }
      .box
      {
        border-radius: 0 0 0 0;
      }
      .box .box-header 
      {
        border-radius: 0 0 0 0;
      }
      .box .box-footer 
      {
        border-radius: 0 0 0 0;
      }
      .btn-primary 
      {
        background-color: #337ab7 !important;
        color: white;
      }
      .btn-success 
      {
        background-color: #5cb85c !important;
      }
      .btn-warning 
      {
        background-color: #f0ad4e !important;
      }
      .btn-info
      {
        background-color: #5bc0de !important;
      }
      .btn-danger {
        background-color: #d9534f !important;
      }
      .skin-blue .wrapper, .skin-blue .main-sidebar, .skin-blue .left-side {
        background-color: #e4e4e4 !important;
      }
      .btn-primary:hover, .btn-primary:active, .btn-primary.hover {
          background-color: #337ab7 !important;
          color: white;
      }
    </style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlackScholes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/market_values/_calculator_form.html.erb
<%= simple_form_for(@market_value,:remote=>true,:url=>result_market_values_path) do |f| %>
  <div class="form-inputs">
    <%= f.association :direction,:include_blank=>"Select Direction" %>
    <%= f.input :user_id,:input_html=>{:value=>current_user.id},:as=>:hidden %>
    <%= f.input :stock_price %>
    <%= f.input :strike_price %>
    <%= f.input :volatility %>
    <%= f.input :interest_rate %>
    <%= f.input :maturity_time %>
  </div>

  <div class="form-actions">
    <%= f.button :submit ,"Calculate",:class=>"btn btn-primary"%>
  </div>
<% end %>

app/views/market_values/_form.html.erb
<%= simple_form_for(@market_value,:remote=>true) do |f| %>
  <div class="form-inputs">
    <%= f.association :direction ,:include_blank=>"Select Direction"%>
    <%= f.input :user_id,:input_html=>{:value=>current_user.id},:as=>:hidden %>
    <%= f.input :stock_price %>
    <%= f.input :strike_price %>
    <%= f.input :volatility %>
    <%= f.input :interest_rate %>
    <%= f.input :maturity_time %>
  </div>

  <div class="form-actions">
    <%= link_to 'Cancel' , new_market_value_path,:remote=>true ,:class=>"btn btn-danger"%>
    <%= f.button :submit ,:class=>"pull-right btn-primary"%>
  </div> 
  
<% end %>

app/views/market_values/_market_data.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Direction</th>
      <th>Stock price</th>
      <th>Strike price</th>
      <th>Volatility</th>
      <th>Interest rate</th>
      <th>Maturity time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @market_values.each do |market_value| %>
      <tr>
        <td><%= market_value.direction.name %></td>
        <td><%= market_value.stock_price %></td>
        <td><%= market_value.strike_price %></td>
        <td><%= market_value.volatility %></td>
        <td><%= market_value.interest_rate %></td>
        <td><%= market_value.maturity_time %></td>
        <td>
          <%= link_to market_value ,:title=>"Result",:remote=>true do%>
            <i class="fa fa-line-chart fa-2x" aria-hidden="true"></i>
          <%end%>
        </td>
        <td>
          <%= link_to edit_market_value_path(market_value) ,:title=>"Edit",:remote=>true do%>
            <i class="fa fa-pencil-square-o fa-2x" aria-hidden="true"></i>
          <%end%>
        </td>
        <td>
          <%= link_to  market_value, method: :delete, data: { confirm: 'Are you sure?' } ,:title=>"Delete",:remote=>true do%>
            <i class="fa fa-trash-o fa-2x" aria-hidden="true"></i>
          <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="col-md-12">
  <%= will_paginate @market_values, renderer: BootstrapPagination::Rails ,:class=>"pull-right"%>
</div>

app/views/market_values/_result.html.erb
<%if @result.present?%>
  <div class="box">
    <div class="box-header with-border">
      <h3 class="box-title">Results</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <table class="table table-bordered">
        <tbody><tr>
          <th style="width: 10px">#</th>
          <th>Parameters</th>
          <th>Call</th>
          <th>Put</th>
        </tr>
        <tr>
          <td>1.</td>
          <td>Option Value</td>
          <td><span class="badge bg-light-blue"><%= @result.option_call%></span></td>
          <td><span class="badge bg-green"><%= @result.option_put%></span></td>
        </tr>
        <tr>
          <td>2.</td>
          <td>Delta </td>
          <td><span class="badge bg-light-blue"><%= @result.delta_call%></span></td>
          <td><span class="badge bg-green"><%= @result.delta_put%></span></td>
        </tr>
        <tr>
          <td>3.</td>
          <td>Gamma</td>
          <td><span class="badge bg-light-blue"><%= @result.gamma%></span></td>
          <td><span class="badge bg-green"><%= @result.gamma%></span></td>
        </tr>
        <tr>
          <td>4.</td>
          <td>Theta</td>
          <td><span class="badge bg-light-blue"><%= @result.theta_call%></span></td>
          <td><span class="badge bg-green"><%= @result.theta_put%></span></td>
        </tr>
        <tr>
          <td>5.</td>
          <td>Vega</td>
          <td><span class="badge bg-light-blue"><%= @result.vega%></span></td>
          <td><span class="badge bg-green"><%= @result.vega%></span></td>
        </tr>
        <tr>
          <td>6.</td>
          <td>Rho</td>
          <td><span class="badge bg-light-blue"><%= @result.rho_call%></span></td>
          <td><span class="badge bg-green"><%= @result.rho_put%></span></td>
        </tr>
        <tr>
          <td>7.</td>
          <td>D1</td>
          <td><span class="badge bg-light-blue"><%= @result.d_one%></span></td>
          <td><span class="badge bg-green"><%= @result.d_one%></span></td>
        </tr>
        <tr>
          <td>8.</td>
          <td>D2</td>
          <td><span class="badge bg-light-blue"><%= @result.d_two%></span></td>
          <td><span class="badge bg-green"><%= @result.d_two%></span></td>
        </tr>
      </tbody></table>
    </div>
  </div>
<%end%>

app/views/market_values/calculator.html.erb
<div class="col-md-2">
	<div class="box">
		<div class="box-body" id="calculator">
			<%= render 'calculator_form'%>
		</div>
	</div>
</div>
<div class="col-md-5" id="result">
	<%= render 'result'%>
</div>
<div class="col-md-5" id="graph">
	<%= render 'result_graph'%>
</div>

app/views/market_values/destroy.js.erb
<% if @status == true%>
	$('#market-form').html("<%= j (render 'form') %>");
	$('#market_data').html("<%= j (render 'market_data') %>");
<%else%>
	$('#market-form').html("<%= j (render 'form') %>");
<%end%>

app/views/market_values/edit.html.erb
<h1>Editing Market Value</h1>

<%= render 'form', market_value: @market_value %>

<%= link_to 'Show', @market_value %> |
<%= link_to 'Back', market_values_path %>

app/views/market_values/edit.js.erb
$('#market-form').html("<%= j (render 'form') %>");

app/views/market_values/index.html.erb
<div class="col-md-4">
  <div class="box">
    <div class="box-body" id="market-form">
      <%= render "form"%>
    </div>
  </div>
</div>
<div class="col-md-8">
  <div class="box">
    <div class="box-header with-border">
      <h3 class="box-title">Market values</h3>
    </div>
    <div class="box-body" id='market_data'>
      <%= render 'market_data'%>
    </div>
  </div>
</div>

<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body" id="modal-result">

      </div>
    </div>
  </div>
</div>

app/views/market_values/new.html.erb
<h1>New Market Value</h1>

<%= render 'form', market_value: @market_value %>

<%= link_to 'Back', market_values_path %>

app/views/market_values/new.js.erb
$('#market-form').html("<%= j (render 'form') %>");

app/views/market_values/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stock price:</strong>
  <%= @market_value.stock_price %>
</p>

<p>
  <strong>Volatility:</strong>
  <%= @market_value.volatility %>
</p>

<p>
  <strong>Interest rate:</strong>
  <%= @market_value.interest_rate %>
</p>

<p>
  <strong>Maturity time:</strong>
  <%= @market_value.maturity_time %>
</p>

<p>
  <strong>Strike price:</strong>
  <%= @market_value.strike_price %>
</p>

<p>
  <strong>Direction:</strong>
  <%= @market_value.direction %>
</p>

<%= link_to 'Edit', edit_market_value_path(@market_value) %> |
<%= link_to 'Back', market_values_path %>

app/views/market_values/show.js.erb
$("#myModal").modal().show('toggle');
$('#modal-result').html("<%= j (render 'result') %>");

app/views/market_values/update.js.erb
<% if @status == true%>
	$('#market-form').html("<%= j (render 'form') %>");
	$('#market_data').html("<%= j (render 'market_data') %>");
<%else%>
	$('#market-form').html("<%= j (render 'form') %>");
<%end%>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>